core/urls.py
from django.urls import  path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('<slug:slug>/',  views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/',  views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/',  views.Delete.as_view(), name='delete'),
    
]

crud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("core:single", args=[self.slug])
    
    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title    


 

core/forms.py
from django import forms
from .models import Core

class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = "__all__"

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView,CreateView,DeleteView

# Create your views here.
class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
     model = Core
     template_name = 'core/single.html' 
     context_object_name = 'post'  

class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')

class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name = 'core/confirm-delete.html'

templates/core/add.html
{% extends 'core/base.html' %} {% load widget_tweaks %} {% block content %}

<div class="container pt-5">
  <form method="post" novalidate>
    {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }}
    {%endfor %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:'form-control' }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}

    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Edit
      </button>
      <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
</div>

{% endblock %}

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include 'core/navbar.html' %} {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>

    {% include 'core/footer.html' %}
  </body>
</html>

templates/core/confirm-delete.html
{% extends 'core/base.html' %} {% block content %}
<div class="container pt-5">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
  </form>
</div>

{% endblock content %}

templates/core/edit.html
{% extends 'core/base.html' %} {% load widget_tweaks %} {% block content %}

<div class="container pt-5">
  <form method="post" novalidate>
    {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }}
    {%endfor %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:'form-control' }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}

    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Edit
      </button>
      <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
</div>

{% endblock %}

templates/core/footer.html
<div class="container">
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        CMS Printer
        <small class="d-block mb-3 text-muted">Another yesterday example</small>
      </div>
      <div class="col-6 col-md">
        <h5>Admin</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Post Admin</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About Us</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Home</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li>
            <a class="text-muted" href="#">Sample Code Resources</a>
          </li>
          <li><a class="text-muted" href="#">YouTube Link</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

templates/core/index.html
{% extends 'core/base.html' %} {% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for core in index %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            src="https://via.placeholder.com/300x100/"
            alt=""
          />
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{ core.get_absolute_url }}">{{ core.title }}</a>
            </h4>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand d-flex align-items-center" href="#"
    ><svg
      class="bi bi-display-fill mr-2"
      width="1em"
      height="1em"
      viewBox="0 0 16 16"
      xmlns="http://www.w3.org/2000/svg"
    ></svg>
    Primer
  </a>

  <!-- Toggler/collapsibe Button -->
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#collapsibleNavbar"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item active"></li>
    </ul>
  </div>
</nav>

templates/core/posts.html
{% extends 'core/base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg bg-light navbar-light">
  <!-- Brand -->
  <div class="navbar-brand">Post Administration</div>

  <!-- Toggler/collapsibe Button -->
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#collapsibleNavbar"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:add' %}">Add New</a>
      </li>
    </ul>
  </div>
</nav>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for post in post_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            src="https://via.placeholder.com/300x100/"
            alt=""
          />
          <div class="card-body">
            <h4 class="lead">
              <a class="text-dark" href="{% url 'core:single' post.pk %}"
                >{{ post.title }}</a
              >
            </h4>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group" role="group">
                <a
                  href="{{ post.get_absolute_url }}"
                  class="btn btn-sm btn-outline-primary"
                  role="button"
                  aria-pressed="true"
                  >View</a
                >
                <a
                  href="{% url 'core:edit' post.pk %}"
                  class="btn btn-sm btn-outline-secondary"
                  role="button"
                  aria-pressed="true"
                  >Edit</a
                >
                <a
                  href="{% url 'core:delete' post.pk %}"
                  class="btn btn-sm btn-outline-secondary"
                  role="button"
                  aria-pressed="true"
                  >Delete</a
                >
              </div>
              <div class="">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock %} {% comment '' %}
  <a class="nav-link" href="{% url 'core:add' %}">Add New</a>
  <a
    href="{% url 'core:edit' post.pk %}"
    class="btn btn-sm btn-outline-secondary"
    role="button"
    aria-pressed="true"
    >Edit</a
  >
  <a
    href="{% url 'core:delete' post.pk %}"
    class="btn btn-sm btn-outline-secondary"
    role="button"
    aria-pressed="true"
    >Delete</a
  >{% endcomment %}
</div>

templates/core/single.html
{% extends 'core/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-12 pt-5">
      <img
        class="card-img-top"
        src="https://via.placeholder.com/300x100/"
        alt=""
      />
      <h2 class="pt-5">{{post.title}}</h2>
      <p>{{post.excerpt}}</p>
    </div>
  </div>
</div>

{% endblock %}